"""Onboarding wizard API endpoints.
Handles BoM upload/validation, template listing, and config generation for new customers.
"""

import io
import json
import zipfile
from typing import Optional
from fastapi import APIRouter, UploadFile, File
from fastapi.responses import Response
from pydantic import BaseModel

from app.libs.bom_validator import parse_bom
from app.libs.deployment_templates import get_all_templates

router = APIRouter(prefix="/onboarding", tags=["onboarding"])


# ─── Models ──────────────────────────────────────────────────────────────────

class BomDevice(BaseModel):
    model: str
    matched_model: str
    serial: str
    quantity: int
    role: str
    supported: bool


class BomValidationResponse(BaseModel):
    devices: list[BomDevice]
    warnings: list[str]
    errors: list[str]
    gpu_count: int
    switch_count: int
    valid: bool


class DeploymentTemplate(BaseModel):
    id: str
    name: str
    description: str
    gpu_count: Optional[int] = None
    node_count: Optional[int] = None
    su_count: Optional[int] = None
    leaf_switches: Optional[int] = None
    spine_switches: Optional[int] = None
    topology: str
    fabric: str
    bandwidth: str
    use_cases: list[str]
    icon: str


class TopologyConfig(BaseModel):
    template_id: str
    su_count: int
    nodes_per_su: int
    gpus_per_node: int
    leaf_switches_per_su: int
    spine_switches: int
    ip_base: str
    vlan_base: int
    company_name: str
    customer_id: str


class GenerateConfigRequest(BaseModel):
    topology: TopologyConfig
    devices: list[BomDevice]


# ─── Endpoints ───────────────────────────────────────────────────────────────

@router.post("/validate-bom", response_model=BomValidationResponse)
async def validate_bom_upload(file: UploadFile = File(...)):
    """Parse and validate a Bill of Materials file (CSV or Excel)."""
    content = await file.read()
    result = parse_bom(content, file.filename or "upload.csv")
    return BomValidationResponse(
        devices=[BomDevice(**d) for d in result["devices"]],
        warnings=result["warnings"],
        errors=result["errors"],
        gpu_count=result["gpu_count"],
        switch_count=result["switch_count"],
        valid=result["valid"],
    )


@router.get("/templates", response_model=list[DeploymentTemplate])
def list_deployment_templates():
    """Return all available deployment templates."""
    templates = get_all_templates()
    return [
        DeploymentTemplate(
            id=t["id"],
            name=t["name"],
            description=t["description"],
            gpu_count=t["gpu_count"],
            node_count=t["node_count"],
            su_count=t["su_count"],
            leaf_switches=t["leaf_switches"],
            spine_switches=t["spine_switches"],
            topology=t["topology"],
            fabric=t["fabric"],
            bandwidth=t["bandwidth"],
            use_cases=t["use_cases"],
            icon=t["icon"],
        )
        for t in templates
    ]


@router.post("/generate-configs")
def generate_onboarding_configs(request: GenerateConfigRequest):
    """Generate ZTP config bundle and return as downloadable ZIP.
    
    Builds switch configs, DHCP config, cabling matrix, and setup guide
    based on the user's topology configuration and returns as ZIP bytes.
    """
    topo = request.topology
    devices = request.devices
    configs = {}

    # 1. Topology summary JSON
    topology_summary = {
        "customer": topo.company_name,
        "customer_id": topo.customer_id,
        "template": topo.template_id,
        "scalable_units": topo.su_count,
        "nodes_per_su": topo.nodes_per_su,
        "gpus_per_node": topo.gpus_per_node,
        "total_gpus": topo.su_count * topo.nodes_per_su * topo.gpus_per_node,
        "leaf_switches_per_su": topo.leaf_switches_per_su,
        "spine_switches": topo.spine_switches,
        "ip_base": topo.ip_base,
        "vlan_base": topo.vlan_base,
        "devices": [d.model_dump() for d in devices],
    }
    configs["topology-summary.json"] = json.dumps(topology_summary, indent=2)

    # 2. DHCP config
    dhcp_lines = [
        "# Auto-generated DHCP config for ZTP",
        f"# Customer: {topo.company_name} ({topo.customer_id})",
        "# Generated by TechTalk Onboarding Wizard",
        "",
        "default-lease-time 600;",
        "max-lease-time 7200;",
        "authoritative;",
        "",
        f"subnet {topo.ip_base}.0 netmask 255.255.255.0 {{",
        f"  range {topo.ip_base}.10 {topo.ip_base}.200;",
        f"  option routers {topo.ip_base}.1;",
        "  option domain-name-servers 8.8.8.8;",
        "",
        "  # ZTP Boot options",
        "  if exists user-class and option user-class = \"SONiC-ZTP\" {",
        "    option bootfile-name \"http://ztp-server/ztp/discovery-script\";",
        "  }",
        "}",
    ]
    configs["dhcp.conf"] = "\n".join(dhcp_lines)

    # 3. Cabling matrix CSV
    cabling_lines = ["source_device,source_port,dest_device,dest_port,cable_type,speed"]
    for su in range(1, topo.su_count + 1):
        for leaf in range(1, topo.leaf_switches_per_su + 1):
            for node in range(1, topo.nodes_per_su + 1):
                for gpu in range(topo.gpus_per_node):
                    cabling_lines.append(
                        f"SU{su}-Leaf{leaf},Eth{node}/{gpu+1},"
                        f"SU{su}-Node{node},GPU{gpu},OSFP-400G,400G"
                    )
        if topo.spine_switches > 0:
            for leaf in range(1, topo.leaf_switches_per_su + 1):
                for spine in range(1, topo.spine_switches + 1):
                    cabling_lines.append(
                        f"SU{su}-Leaf{leaf},Uplink{spine},"
                        f"Spine{spine},SU{su}-Port{leaf},QSFP-400G,400G"
                    )
    configs["cabling-matrix.csv"] = "\n".join(cabling_lines)

    # 4. Per-switch stub configs
    for su in range(1, topo.su_count + 1):
        for leaf in range(1, topo.leaf_switches_per_su + 1):
            switch_name = f"SU{su}-Leaf{leaf}"
            vlan = topo.vlan_base + (su - 1) * 10 + leaf
            ip_last = 10 + (su - 1) * 20 + leaf
            switch_cfg = f"""# {switch_name} - Auto-generated ZTP config stub
# Customer: {topo.company_name}
# VLAN: {vlan}

hostname {switch_name}

vlan {vlan}
  name gpu-fabric-su{su}-leaf{leaf}

interface Management0
  ip address {topo.ip_base}.{ip_last}/24
  no shutdown

"""
            for port in range(1, topo.nodes_per_su + 1):
                switch_cfg += f"interface Ethernet{port}\n  description GPU-Node{port}\n  speed 400g\n  no shutdown\n"
            configs[f"switch-configs/{switch_name}.conf"] = switch_cfg

    # 5. Setup guide
    total_gpus = topo.su_count * topo.nodes_per_su * topo.gpus_per_node
    guide = f"""# TechTalk ZTP Setup Guide
## Customer: {topo.company_name}
## Deployment: {topo.template_id}
## Total GPUs: {total_gpus}

---

## Step 1: Deploy DHCP Server
1. Copy `dhcp.conf` to your DHCP server
2. Restart DHCP: `sudo systemctl restart isc-dhcp-server`
3. Verify switches can reach DHCP on management VLAN

## Step 2: Set Up ZTP Server
1. Ensure TechTalk ZTP API is reachable at your ZTP server URL
2. Import `cabling-matrix.csv` into TechTalk
3. Upload schematic/BoM to validate inventory

## Step 3: Cable the Hardware
Follow `cabling-matrix.csv` for all switch-to-GPU connections.
Each row = one physical cable.

## Step 4: Power On Switches
Switches will:
  1. DHCP-boot and receive discovery script
  2. Report serial numbers to TechTalk
  3. Download full config from /ztp/config/{{mac}}
  4. Apply config and reboot into final state

## Step 5: Monitor Provisioning
Open TechTalk dashboard -> Provisioning view to watch real-time status.

## Network Summary
- SUs: {topo.su_count}
- Nodes/SU: {topo.nodes_per_su}
- GPUs/Node: {topo.gpus_per_node}
- Leaf switches/SU: {topo.leaf_switches_per_su}
- Spine switches: {topo.spine_switches}
- Management subnet: {topo.ip_base}.0/24
- Base VLAN: {topo.vlan_base}
"""
    configs["SETUP-GUIDE.md"] = guide

    # Build ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, content in configs.items():
            zf.writestr(path, content)
    zip_buffer.seek(0)
    zip_bytes = zip_buffer.read()

    filename = f"{topo.customer_id}-ztp-configs.zip"
    return Response(
        content=zip_bytes,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
