
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



import AdminApproval from "./pages/AdminApproval.tsx";
import AdminDashboard from "./pages/AdminDashboard.tsx";
import AdminDocuments from "./pages/AdminDocuments.tsx";
import AdminModeration from "./pages/AdminModeration.tsx";
import AdminSettings from "./pages/AdminSettings.tsx";
import AdminSystem from "./pages/AdminSystem.tsx";
import AdminUsers from "./pages/AdminUsers.tsx";
import App from "./pages/App.tsx";
import BulkImport from "./pages/BulkImport.tsx";
import CompanyAdminDashboard from "./pages/CompanyAdminDashboard.tsx";
import ConstraintManagement from "./pages/ConstraintManagement.tsx";
import ExpertSubmission from "./pages/ExpertSubmission.tsx";
import FirebaseSetup from "./pages/FirebaseSetup.tsx";
import GpuClusterBringupPage from "./pages/GpuClusterBringupPage.tsx";
import HistoricRecords from "./pages/HistoricRecords.tsx";
import History from "./pages/History.tsx";
import KnowledgeBaseSearch from "./pages/KnowledgeBaseSearch.tsx";
import LiveClusterDashboard from "./pages/LiveClusterDashboard.tsx";
import Login from "./pages/Login.tsx";
import Logout from "./pages/Logout.tsx";
import MediaCapture from "./pages/MediaCapture.tsx";
import MyReports from "./pages/MyReports.tsx";
import Register from "./pages/Register.tsx";
import Response from "./pages/Response.tsx";
import Search from "./pages/Search.tsx";
import SessionChatPage from "./pages/SessionChatPage.tsx";
import SessionCreate from "./pages/SessionCreate.tsx";
import SystemAdminDashboard from "./pages/SystemAdminDashboard.tsx";
import TextCommandsPage from "./pages/TextCommandsPage.tsx";
import TroubleshootingSessionPage from "./pages/TroubleshootingSessionPage.tsx";
import VoiceCommands from "./pages/VoiceCommands.tsx";
import ZipImport from "./pages/ZipImport.tsx";
import DesignCalculator from "./pages/DesignCalculator.tsx";

export const userRoutes: RouteObject[] = [



	{ path: "/admin-approval", element: <UserGuard><AdminApproval /></UserGuard> },
	{ path: "/adminapproval", element: <UserGuard><AdminApproval /></UserGuard> },
	{ path: "/admin-dashboard", element: <UserGuard><AdminDashboard /></UserGuard> },
	{ path: "/admindashboard", element: <UserGuard><AdminDashboard /></UserGuard> },
	{ path: "/admin-documents", element: <UserGuard><AdminDocuments /></UserGuard> },
	{ path: "/admindocuments", element: <UserGuard><AdminDocuments /></UserGuard> },
	{ path: "/admin-moderation", element: <UserGuard><AdminModeration /></UserGuard> },
	{ path: "/adminmoderation", element: <UserGuard><AdminModeration /></UserGuard> },
	{ path: "/admin-settings", element: <UserGuard><AdminSettings /></UserGuard> },
	{ path: "/adminsettings", element: <UserGuard><AdminSettings /></UserGuard> },
	{ path: "/admin-system", element: <UserGuard><AdminSystem /></UserGuard> },
	{ path: "/adminsystem", element: <UserGuard><AdminSystem /></UserGuard> },
	{ path: "/admin-users", element: <UserGuard><AdminUsers /></UserGuard> },
	{ path: "/adminusers", element: <UserGuard><AdminUsers /></UserGuard> },
	{ path: "/", element: <App /> },
	{ path: "/design-calculator", element: <DesignCalculator /> },
	{ path: "/designcalculator", element: <DesignCalculator /> },
	{ path: "/bulk-import", element: <UserGuard><BulkImport /></UserGuard> },
	{ path: "/bulkimport", element: <UserGuard><BulkImport /></UserGuard> },
	{ path: "/company-admin-dashboard", element: <UserGuard><CompanyAdminDashboard /></UserGuard> },
	{ path: "/companyadmindashboard", element: <UserGuard><CompanyAdminDashboard /></UserGuard> },
	{ path: "/constraint-management", element: <ConstraintManagement /> },
	{ path: "/constraintmanagement", element: <ConstraintManagement /> },
	{ path: "/expert-submission", element: <UserGuard><ExpertSubmission /></UserGuard> },
	{ path: "/expertsubmission", element: <UserGuard><ExpertSubmission /></UserGuard> },
	{ path: "/firebase-setup", element: <UserGuard><FirebaseSetup /></UserGuard> },
	{ path: "/firebasesetup", element: <UserGuard><FirebaseSetup /></UserGuard> },
	{ path: "/gpu-cluster-bringup-page", element: <GpuClusterBringupPage /> },
	{ path: "/gpuclusterbringuppage", element: <GpuClusterBringupPage /> },
	{ path: "/historic-records", element: <HistoricRecords /> },
	{ path: "/historicrecords", element: <HistoricRecords /> },
	{ path: "/history", element: <UserGuard><History /></UserGuard> },
	{ path: "/knowledge-base-search", element: <UserGuard><KnowledgeBaseSearch /></UserGuard> },
	{ path: "/knowledgebasesearch", element: <UserGuard><KnowledgeBaseSearch /></UserGuard> },
	{ path: "/live-cluster-dashboard", element: <LiveClusterDashboard /> },
	{ path: "/liveclusterdashboard", element: <LiveClusterDashboard /> },
	{ path: "/login", element: <Login /> },
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard> },
	{ path: "/media-capture", element: <UserGuard><MediaCapture /></UserGuard> },
	{ path: "/mediacapture", element: <UserGuard><MediaCapture /></UserGuard> },
	{ path: "/my-reports", element: <UserGuard><MyReports /></UserGuard> },
	{ path: "/myreports", element: <UserGuard><MyReports /></UserGuard> },
	{ path: "/register", element: <UserGuard><Register /></UserGuard> },
	{ path: "/response", element: <UserGuard><Response /></UserGuard> },
	{ path: "/search", element: <UserGuard><Search /></UserGuard> },
	{ path: "/session-chat-page", element: <UserGuard><SessionChatPage /></UserGuard> },
	{ path: "/sessionchatpage", element: <UserGuard><SessionChatPage /></UserGuard> },
	{ path: "/session-create", element: <UserGuard><SessionCreate /></UserGuard> },
	{ path: "/sessioncreate", element: <UserGuard><SessionCreate /></UserGuard> },
	{ path: "/system-admin-dashboard", element: <UserGuard><SystemAdminDashboard /></UserGuard> },
	{ path: "/systemadmindashboard", element: <UserGuard><SystemAdminDashboard /></UserGuard> },
	{ path: "/text-commands-page", element: <UserGuard><TextCommandsPage /></UserGuard> },
	{ path: "/textcommandspage", element: <UserGuard><TextCommandsPage /></UserGuard> },
	{ path: "/troubleshooting-session-page", element: <UserGuard><TroubleshootingSessionPage /></UserGuard> },
	{ path: "/troubleshootingsessionpage", element: <UserGuard><TroubleshootingSessionPage /></UserGuard> },
	{ path: "/voice-commands", element: <UserGuard><VoiceCommands /></UserGuard> },
	{ path: "/voicecommands", element: <UserGuard><VoiceCommands /></UserGuard> },
	{ path: "/zip-import", element: <UserGuard><ZipImport /></UserGuard> },
	{ path: "/zipimport", element: <UserGuard><ZipImport /></UserGuard> },

];
